source "https://rubygems.org"

# Specify your gem's dependencies in currency_converter_engine.gemspec.
gemspec

gem "puma"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
gem "debug", ">= 1.0.0"

gem "dotenv-rails", "~> 3.1"

gem 'http_wrapper', path: '../../http_wrapper'

gem 'shared_services', path: '../../shared_services'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
end

group :test do
  gem 'factory_bot_rails'  # Opcional, útil para crear datos de prueba
  gem 'faker'              # Opcional, útil para generar datos falsos
end

