source "https://rubygems.org"

# Specify your gem's dependencies in weather_engine.gemspec.
gemspec

gem "puma"

gem "sprockets-rails"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]

gem "debug", ">= 1.0.0"

gem "dotenv-rails", "~> 3.1"

gem 'http_wrapper', path: '../../http_wrapper'


